mindwiki/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView

admin.site.site_header = "MindWiki"
admin.site.site_title = "MindWiki"
admin.site.index_title = "MindWiki Administration"

urlpatterns = [
    path('', RedirectView.as_view(url='/wiki/')),
    path('favicon.ico', RedirectView.as_view(url='/static/favicon.ico')),
    path('wiki/', include('wiki.urls')),
    path('wordcloud/', include('word_cloud.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

mymindwiki/urls.py
"""mymindwiki URL Configuration

"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView

admin.site.site_header = "MindWiki"
admin.site.site_title = "MindWiki"
admin.site.index_title = "MindWiki Administration"

urlpatterns = [
    path('', RedirectView.as_view(url='/wiki/')),
    path('favicon.ico', RedirectView.as_view(url='/static/favicon.ico')),
    path('wiki/', include('mindwiki.urls')),
    path('wordcloud/', include('word_cloud.urls')),
    path('admin/', admin.site.urls),
    path('markdownx/', include('markdownx.urls')),
    path("select2/", include("django_select2.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

word_cloud/urls.py
from django.urls import path

from . import views

app_name = 'word_cloud'
urlpatterns = [
    path('create/', views.create_word_cloud, name='create'),
]

word_cloud/models.py
from django.db import models

# Create your models here.

wiki/views.py
__all__ = ['PageCreateView', 'PageDetailView', 'PageListView',
           'PageSearchView', 'PageUpdateView', 'WebLinkDetailView']

from django.http import JsonResponse
from django.views import generic, View

from .models import Page, WebLink
from .forms import PageForm


class PageCreateView(generic.CreateView):
    model = Page
    form_class = PageForm
    template_name = 'pages/edit.html'


class PageUpdateView(generic.UpdateView):
    model = Page
    form_class = PageForm
    template_name = 'pages/edit.html'


class PageListView(generic.ListView):
    context_object_name = 'latest_page_list'
    model = Page
    ordering = '-date_created'
    paginate_by = 9
    template_name = 'pages/list.html'


class PageDetailView(generic.DetailView):
    model = Page
    template_name = 'pages/detail.html'


class PageSearchView(generic.ListView):
    context_object_name = 'search_results'
    paginate_by = 9
    template_name = 'pages/search.html'

    def get_queryset(self):
        contains = self.request.GET.get('contains', None)
        tags = self.request.GET.get('tags', None)

        query_set = Page.objects.all()
        if tags is not None and tags != '':
            for tag in tags.split(','):
                query_set = query_set.filter(tags__name__contains=tag)
        if contains is not None and contains != '':
            query_set = query_set.filter(
                body__contains=contains) | query_set.filter(
                title__contains=contains)
        return query_set


class WebLinkDetailView(generic.DetailView):
    model = WebLink

    def get(self, request, *args, **kwargs):
        json_requested = self.request.GET.get('json', False)
        if json_requested and json_requested.lower() =='true':
            weblink = self.get_object()
            data = {
                'description': weblink.description,
                'url': weblink.url,
            }
            return JsonResponse({'data': data})
        return super().get(request, *args, **kwargs)

word_cloud/views.py
import io

from django.http import HttpResponse
from django.views.decorators.http import require_GET
from wordcloud import WordCloud


@require_GET
def create_word_cloud(request):
    width = request.GET['width']
    height = request.GET['height']
    bg_color = tuple(int(request.GET['bg'][i:i + 2], 16) for i in (0, 2, 4))
    words = request.GET['words'].replace(' ', '').replace('-', '')
    cmap = request.GET['cmap']

    wc = WordCloud(width=int(width),
                   height=int(height),
                   background_color=bg_color,
                   repeat=True,
                   colormap=cmap, )
    img = wc.generate(words)
    f = io.BytesIO()
    img.to_image().save(f, format='png')
    f.seek(0)
    return HttpResponse(f.read(), content_type='image/png')

mymindwiki/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
            crossorigin="anonymous"></script>
    {% block metatags %}<title></title>{% endblock %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <style>
        body {
            background-color: rgb(245, 247, 245);
        }
        .mw-pj-st-ns {
            background-color: rgb(64, 64, 64);
        }
        .mw-pj-st-ip {
            background-color: rgb(10, 183, 10);
        }
        .mw-pj-st-b {
            background-color: rgb(224, 92, 32);
        }

        .mw-pj-st-c {
            background-color: rgb(84, 62, 41);
        }
    </style>
</head>
<body>
<div id="bodydiv">
    <div id="nofooter">
        <nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="topnav" aria-label="">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'mindwiki:index' %}">
                    <img src="/static/icons/logo.svg" width="50" height="30" class="d-inline-block rounded align-top"
                         alt="logo" loading="lazy">
                    MindWiki
                </a>
                <div class="nav justify-content-end">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'mindwiki:index' %}">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarBrowseDropdown" role="button"
                               data-bs-toggle="dropdown" aria-expanded="false">
                                Browse
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarBrowseDropdown">
                                <li>
                                    <a class="dropdown-item" href="{% url 'mindwiki:category-index' %}">Categories</a>
                                </li>
                                <li><a class="dropdown-item" href="{% url 'mindwiki:file-index' %}">Files</a></li>
                                <li><a class="dropdown-item" href="{% url 'mindwiki:image-index' %}">Images</a></li>
                                <li><a class="dropdown-item" href="{% url 'mindwiki:page-index' %}">Pages</a></li>
                                <li><a class="dropdown-item" href="{% url 'mindwiki:project-index' %}">Projects</a></li>
                                <li><a class="dropdown-item" href="{% url 'mindwiki:snippet-index' %}">Snippets</a></li>
                                <li><a class="dropdown-item" href="{% url 'mindwiki:tag-index' %}">Tags</a></li>
                                <li><a class="dropdown-item" href="{% url 'mindwiki:weblink-index' %}">WebLinks</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarSearchDropdown" role="button"
                               data-bs-toggle="dropdown" aria-expanded="false">
                                Search
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarSearchDropdown">
                                <li>
                                    <a class="dropdown-item" href="{% url 'mindwiki:category-search' %}">Categories</a>
                                </li>
                                <li><a class="dropdown-item" href="{% url 'mindwiki:file-search' %}">Files</a></li>
                                <li><a class="dropdown-item" href="{% url 'mindwiki:image-search' %}">Images</a></li>
                                <li><a class="dropdown-item" href="{% url 'mindwiki:page-search' %}">Pages</a></li>
                                <li>
                                    <a class="dropdown-item" href="{% url 'mindwiki:project-search' %}">Projects</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="{% url 'mindwiki:snippet-search' %}">Snippets</a>
                                </li>
                                <li><a class="dropdown-item" href="{% url 'mindwiki:tag-search' %}">Tags</a></li>
                                <li><a class="dropdown-item" href="{% url 'mindwiki:weblink-search' %}">WebLinks</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'admin:index' %}" tabindex="-1">Admin</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        {% block content %}
        {% endblock content %}
    </div>
    <footer class="footer" id="foot">
        <div class="container"><h5 style="text-align:center;"></h5>
            <nav class="navbar navbar-expand-lg" aria-label="">
                <div class="container-fluid">
                    <p></p>
                    <div class="nav justify-content-center" id="navfooter">
                        <span><a class="nav-link text-black font-weight-bold"
                                 href="{% url 'mindwiki:index' %}">About</a></span>
                        <span><a class="nav-link text-black font-weight-bold"
                                 href="https://github.com/ravenoak/mindwiki.py">GitHub</a></span>
                        <span><a class="nav-link text-black font-weight-bold" href="{% url 'mindwiki:index' %}"></a></span>
                        <span><a class="nav-link text-black font-weight-bold" href="#"></a></span>
                    </div>
                </div>
            </nav>
        </div>
    </footer>
</div>
</body>
</html>

mymindwiki/templates/mindwiki/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
            crossorigin="anonymous"></script>
    {% block metatags %}<title></title>{% endblock %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <style>
        body {
            background-color: rgb(245, 247, 245);
        }
        .mw-pj-st-ns {
            background-color: rgb(64, 64, 64);
        }
        .mw-pj-st-ip {
            background-color: rgb(10, 183, 10);
        }
        .mw-pj-st-b {
            background-color: rgb(224, 92, 32);
        }

        .mw-pj-st-c {
            background-color: rgb(84, 62, 41);
        }
    </style>
</head>
<body>
<div id="bodydiv">
    <div id="nofooter">
        <nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="topnav" aria-label="">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'mindwiki:index' %}">
                    <img src="/static/icons/logo.svg" width="50" height="30" class="d-inline-block rounded align-top"
                         alt="logo" loading="lazy">
                    MindWiki
                </a>
                <div class="nav justify-content-end">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'mindwiki:index' %}">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarBrowseDropdown" role="button"
                               data-bs-toggle="dropdown" aria-expanded="false">
                                Browse
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarBrowseDropdown">
                                <li>
                                    <a class="dropdown-item" href="">Categories</a>
                                </li>
                                <li><a class="dropdown-item" href="">Files</a></li>
                                <li><a class="dropdown-item" href="">Images</a></li>
                                <li><a class="dropdown-item" href="">Pages</a></li>
                                <li><a class="dropdown-item" href="">Projects</a></li>
                                <li><a class="dropdown-item" href="">Snippets</a></li>
                                <li><a class="dropdown-item" href="">Tags</a></li>
                                <li><a class="dropdown-item" href="">WebLinks</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarSearchDropdown" role="button"
                               data-bs-toggle="dropdown" aria-expanded="false">
                                Search
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarSearchDropdown">
                                <li>
                                    <a class="dropdown-item" href="">Categories</a>
                                </li>
                                <li><a class="dropdown-item" href="">Files</a></li>
                                <li><a class="dropdown-item" href="">Images</a></li>
                                <li><a class="dropdown-item" href="">Pages</a></li>
                                <li>
                                    <a class="dropdown-item" href="">Projects</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="">Snippets</a>
                                </li>
                                <li><a class="dropdown-item" href="">Tags</a></li>
                                <li><a class="dropdown-item" href="">WebLinks</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'admin:index' %}" tabindex="-1">Admin</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        {% block content %}
        {% endblock content %}
    </div>
    <footer class="footer" id="foot">
        <div class="container"><h5 style="text-align:center;"></h5>
            <nav class="navbar navbar-expand-lg" aria-label="">
                <div class="container-fluid">
                    <p></p>
                    <div class="nav justify-content-center" id="navfooter">
                        <span><a class="nav-link text-black font-weight-bold"
                                 href="{% url 'mindwiki:index' %}">About</a></span>
                        <span><a class="nav-link text-black font-weight-bold"
                                 href="https://github.com/ravenoak/mindwiki.py">GitHub</a></span>
                        <span><a class="nav-link text-black font-weight-bold" href="{% url 'mindwiki:index' %}"></a></span>
                        <span><a class="nav-link text-black font-weight-bold" href="#"></a></span>
                    </div>
                </div>
            </nav>
        </div>
    </footer>
</div>
</body>
</html>

wiki/templates/pages/detail.html
{% extends "base.html" %}
{% load static %}
{% load markdown_extras %}
{% block metatags %}
    <link href="/static/pages/css/codehilite-colorful.css" rel="stylesheet"/>
    <title>{{ page.title }} | MindWiki</title>
    <meta name="description" content="A Wiki to organize your thoughts">
    <meta property="og:title" content="{{ page.title }}">
    <meta property="og:site_name" content="MindWiki">
    <meta property="og:url" content="http://localhost">
    <meta property="og:description" content="A Wiki to organize your thoughts">
    <meta property="og:type" content="website">
{% endblock %}
{% block content %}
    <header class="jumbotron">
        <div class="container">
            <nav id="page-nav" class="navbar navbar-expand-lg shadow">
                <div class="container-fluid">
                    <p class="h1"><strong>{{ page.title }}</strong></p>
                </div>
                <div class="nav justify-content-end">
                    <div class="d-inline">
                        <a class="nav-link text-black font-weight-bold" href="{% url 'admin:wiki_page_change' page.pk %}">edit</a>
                    </div>
                </div>
            </nav>
        </div>
    </header>
    <div class="container">
        <div class="row">
            <div class="col-md-8 mt-3 left">
                <div>{{ page.body | markdown | safe }}</div>
                <div>
                    Tags:
                    <ul>
                        {% for tag in page.tags.all %}
                            <li>{{ tag.name }}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

wiki/templates/pages/list.html
{% extends "base.html" %}
{% load static %}
{% block metatags %}
    <title>Page List | MindWiki</title>
    <meta name="description" content="A Wiki to organize your thoughts">
    <meta property="og:title" content="Page List">
    <meta property="og:site_name" content="MindWiki">
    <meta property="og:url" content="http://localhost">
    <meta property="og:description" content="A Wiki to organize your thoughts">
    <meta property="og:type" content="website">
{% endblock %}
{% block content %}
    <header class="jumbotron">
        <div class="container">
            <nav id="page-nav" class="navbar navbar-expand-lg shadow">
                <div class="container-fluid">
                    <p class="h1">Welcome to the <strong>MindWiki</strong></p>
                </div>
                <div class="nav justify-content-end">
                    <div class="d-inline">
                        <a class="nav-link text-black font-weight-bold" href="{% url 'admin:wiki_page_add' %}">add</a>
                    </div>
                </div>
            </nav>
        </div>
    </header>
    <div class="container">
        <div class="row">
            <div class="col-md-8 mt-3 left">
                {% if latest_page_list %}
                    {% for page in latest_page_list %}
                        <div class="shadow-none card mb-4" id="newsfeed"
                             style="background-image: url({% url 'word_cloud:create' %}?width=350&height=70&bg=F1F8E9&words={{ page.tags.all|join:'.'|urlencode }}&cmap=Set2); background-repeat: no-repeat; background-position: right; background-color: #F1F8E9;">
                            <div class="card-body">
                                <h3 class="card-title"><a href="{% url 'wiki:page-detail' page.slug %}">{{ page.title }}</a>
                                </h3>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <p>No pages are available.</p>
                {% endif %}
            </div>
        </div>
        <div class="row">
            <div class="pagination">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                        <a href="?page=1">&laquo; first</a>
                        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}
                    <span class="current">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</span>
                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">next</a>
                        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                </span>
            </div>
        </div>
    </div>
{% endblock %}

wiki/templates/pages/search.html
{% extends "base.html" %}
{% load static %}
{% load markdown_extras %}
{% block metatags %}
    <title>Search | MindWiki</title>
    <meta name="description" content="A Wiki to organize your thoughts">
    <meta property="og:title" content="Search">
    <meta property="og:site_name" content="MindWiki">
    <meta property="og:url" content="http://localhost">
    <meta property="og:description" content="A Wiki to organize your thoughts">
    <meta property="og:type" content="website">
{% endblock %}
{% block content %}
    <header class="jumbotron">
        <div class="container">
            <p class="h1">Search the <strong>MindWiki</strong></p>
        </div>
    </header>
    <div class="container">
        <div class="row">
            <form method="get">
                <div class="mb-3">
                    <label for="contains" class="form-label">Contains</label>
                    <input type="search" id="contains" name="contains">
                    <div id="containsHelpBlock" class="form-text">
                        Performs a sub-string search on the <strong>body</strong> and <strong>title</strong> fields.
                    </div>
                </div>
                <div class="mb-3">
                    <label for="tags" class="form-label">Tags</label>
                    <input type="search" id="tags" name="tags">
                    <div id="tagsHelpBlock" class="form-text">
                        Performs a sub-string search on the <strong>tags</strong> field. Use a comma to separate
                        multiple tags.
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">Search</button>
            </form>
        </div>
        <div class="row">
            <div class="col-md-8 mt-3 left">
                {% if search_results %}
                    {% for page in search_results %}
                        <div class="shadow-none card mb-4" id="newsfeed"
                             style="background-image: url({% url 'word_cloud:create' %}?width=350&height=70&bg=F1F8E9&words={{ page.tags.all|join:'.'|urlencode }}&cmap=Set2); background-repeat: no-repeat; background-position: right; background-color: #F1F8E9;">
                            <div class="card-body">
                                <h3 class="card-title">
                                    <a href="{% url 'wiki:page-detail' page.slug %}">{{ page.title }}</a>
                                </h3>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <p>No pages are available.</p>
                {% endif %}
            </div>
        </div>
        <div class="row">
            <div class="pagination">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                        <a href="?page=1">&laquo; first</a>
                        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}
                    <span class="current">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</span>
                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">next</a>
                        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                </span>
            </div>
        </div>
    </div>
{% endblock %}

wiki/templates/wiki/weblink_detail.html
{% extends "base.html" %}
{% load static %}
{% load markdown_extras %}
{% block metatags %}
    <title>{{ weblink.slug }} | Weblink | MindWiki</title>
    <meta name="description" content="A Wiki to organize your thoughts">
    <meta property="og:title" content="weblink-{{ weblink.slug }}">
    <meta property="og:site_name" content="MindWiki">
    <meta property="og:url" content="http://localhost">
    <meta property="og:description" content="A Wiki to organize your thoughts">
    <meta property="og:type" content="website">
{% endblock %}
{% block content %}
    <header class="jumbotron">
        <div class="container">
            <nav id="page-nav" class="navbar navbar-expand-lg shadow">
                <div class="container-fluid">
                    <p class="h1"><strong>{{ weblink.slug }}</strong></p>
                </div>
                <div class="nav justify-content-end">
                    <div class="d-inline">
                        <a class="nav-link text-black font-weight-bold" href="{% url 'admin:wiki_weblink_change' weblink.pk %}">edit</a>
                    </div>
                </div>
            </nav>
        </div>
    </header>
    <div class="container">
        <div class="row">
            <div class="col-md-8 mt-3 left">
                <div>{{ weblink.description }}</div>
                <div><a href="{{ weblink.url }}">{{ weblink.url }}</a></div>
                <div>
                    Tags:
                    <ul>
                        {% for tag in weblink.tags.all %}
                            <li>{{ tag.name }}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}